apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelineruns.tekton.dev
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
spec:
  group: tekton.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
    - name: v1beta1
      served: true
      storage: false
  names:
    kind: PipelineRun
    plural: pipelineruns
    categories:
      - tekton
      - tekton-pipelines
    shortNames:
      - pr
      - prs
  scope: Namespaced
  additionalPrinterColumns:
    - name: Succeeded
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Succeeded\")].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Succeeded\")].reason"
    - name: StartTime
      type: date
      JSONPath: .status.startTime
    - name: CompletionTime
      type: date
      JSONPath: .status.completionTime
  # Opt into the status subresource so metadata.generation
  # starts to increment
  subresources:
    status: {}
  version: v1alpha1