name: pipelines
icon: https://tekton.dev/images/tekton-horizontal-color.png
apiVersion: v1
version: 0.11.5
appVersion: 0.11.3
home: https://github.com/tektoncd/pipeline
keywords:
  - helm
  - tekton
  - tektoncd
  - pipeline
  - pipelines
maintainers:
  - name: eddycharly
    email: ceb@agriconomie.com
description: |
  This chart bootstraps installation of [tekton pipeline](https://github.com/tektoncd/pipeline).
